/** Deterministic daily quotes — same data as iOS */
export const QUOTES = [
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Focus is the art of knowing what to ignore.", author: "James Clear" },
  { text: "Small steps every day lead to big changes every year.", author: "Unknown" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Energy flows where attention goes.", author: "Unknown" },
  { text: "Productivity is never an accident. It is always the result of a commitment to excellence.", author: "Paul J. Meyer" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen R. Covey" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "It's not about having time. It's about making time.", author: "Unknown" },
  { text: "Your mind is for having ideas, not holding them.", author: "David Allen" },
  { text: "Clarity is the counterbalance of profound thoughts.", author: "Luc de Clapiers" },
  { text: "Concentrate all your thoughts upon the work in hand.", author: "Alexander Graham Bell" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "It is not that I'm so smart. But I stay with the questions much longer.", author: "Albert Einstein" },
  { text: "You will never find time for anything. If you want time, you must make it.", author: "Charles Buxton" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "First, have a definite, clear practical ideal.", author: "Aristotle" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "You don't need more time. You need more focus.", author: "Unknown" },
  { text: "One task at a time, done with full attention.", author: "Unknown" },
  { text: "Excellence is not a destination but a continuous journey.", author: "Brian Tracy" },
  { text: "Slow is smooth. Smooth is fast.", author: "Unknown" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Deep work is the superpower of the 21st century.", author: "Cal Newport" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
] as const

export type Quote = (typeof QUOTES)[number]
