export type YMD = string; // YYYY-MM-DD
export type HM = string;  // HH:MM

export type ItemType = "event" | "task" | "objective";

export type EventColorKey =
  | "blue"
  | "teal"
  | "green"
  | "yellow"
  | "orange"
  | "red"
  | "purple"
  | "gray"
  | "pink"
  | "birthday";

export type ContactDateKind = "birthday" | "anniversary" | "other";

/**
 * Structured place data saved when the user selects an Apple Maps suggestion.
 * Stored alongside the plain `location` string so both display and map linking work.
 */
export type PlaceData = {
  /** Resolved place name, e.g. "Bell Centre" */
  name: string;
  /** Formatted address string, e.g. "1909 Av des Canadiens-de-Montréal, Montréal, QC" */
  address?: string;
  latitude?: number;
  longitude?: number;
};

export type LocalEvent = {
  id: string;
  title: string;

  allDay: boolean;
  startDate: YMD;
  startTime: HM;
  endDate: YMD;
  endTime: HM;

  timezone?: string; // placeholder for later
  location?: string;
  /**
   * Present only when the user picked an Apple Maps suggestion.
   * If absent, `location` is a free-form custom text (e.g. "Room H203").
   */
  locationPlace?: PlaceData;
  notes?: string;

  color: EventColorKey;
  reminder: "none" | "at_time" | "5min" | "10min" | "30min" | "1h" | "2h" | "1d" | "2d" | "3d" | "5d" | "1w";
  recurrence?: "none" | "daily" | "weekly" | "monthly" | "yearly"; // recurrence pattern

  calendarSource: "local" | "google"; // placeholder
  googleCalendarId?: string; // placeholder

  eventType?: "event" | "birthday"; // distinguish birthdays from regular events
  birthYear?: number; // only for birthday events
  category?: string; // user-defined category (Work, Personal, etc.)

  // ── Contact import fields (backward-compatible, never sent to cloud) ──────
  /** "contacts" when this event was imported from device contacts. */
  source?: "local" | "contacts";
  /** Stable device contact ID — used for idempotent re-import */
  contactId?: string;
  /** What kind of contact date this is */
  contactDateKind?: ContactDateKind;
  /** Original label string from the contact's dates array (e.g. "Anniversary") */
  originalLabel?: string;
};

export type CalItem = {
  id: string;
  type: ItemType;
  title: string;

  date: YMD; // grouping day (start day for events)
  allDay?: boolean;
  startTime?: HM; // for sorting
  endTime?: HM;

  colorKey?: EventColorKey; // for events
  location?: string;

  completed?: boolean; // tasks/objectives

  /** Filled for contact-imported events so icons can be differentiated */
  contactDateKind?: ContactDateKind;

  /**
   * Extra searchable keywords (type label, holiday/birthday, objective name,
   * formatted date). Concatenated and lowercased during search filtering.
   */
  meta?: string;

  /** Set for tasks generated by a training plan — used to deduplicate search results. */
  trainingPlanId?: string;
};
