export type ObjectiveCategory =
  | "Academic"
  | "Career"
  | "Personal"
  | "Health & Fitness"
  | "Skill Development"
  | "Creative"
  | "Misc";

export type ObjectiveColor =
  | "blue"
  | "teal"
  | "green"
  | "yellow"
  | "orange"
  | "red"
  | "purple"
  | "gray";

export type ObjectiveStatus = "active" | "completed";

export type Objective = {
  id: string;
  title: string;
  description?: string;
  category: ObjectiveCategory;
  color: ObjectiveColor;
  deadline?: string; // YYYY-MM-DD
  createdAt: string; // ISO
  status: ObjectiveStatus;
};

export type TaskImportance = 1 | 2 | 3 | 4; // Low / Medium / High / Critical
export type TaskStatus = "not-started" | "in-progress" | "completed";

export type Task = {
  id: string;
  objectiveId: string;
  title: string;
  description?: string;
  deadline?: string; // YYYY-MM-DD
  importance: TaskImportance;
  status: TaskStatus;
  createdAt: string; // ISO
  completedAt?: string | null;
  /** Set when this task was auto-generated by a training plan */
  trainingPlanId?: string;
};

export type CalendarEvent = {
  id: string;
  title: string;
  date: string; // YYYY-MM-DD
  source: "task-deadline" | "manual" | "google";
  meta?: { taskId?: string; objectiveId?: string };
};

// ── Training Plan types ───────────────────────────────────────────────────────

export type TrainingSession = {
  id: string;
  name: string;
  description?: string;
  durationMinutes?: number;
  timeOfDay?: string;
  exercises: string[];
  isRest: boolean;
};

export type CycleDay = {
  id: string;
  label: string;
  sessionId: string; // "" for rest days
  isRest: boolean;
};

export type WeekDayAssignment = {
  dayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6; // 0 = Sun
  sessionId: string | null;
  isRest: boolean;
};

export type TrainingPlanType = "cycle" | "week";
export type MissedBehavior = "keep-order" | "shift-forward";

export type TrainingPlan = {
  id: string;
  objectiveId: string;
  name: string;
  type: TrainingPlanType;
  sessions: TrainingSession[];
  /** Cycle-based: ordered days that repeat */
  cycleDays?: CycleDay[];
  startDate?: string;          // YYYY-MM-DD
  startCycleDayIndex?: number; // which cycle day index is active on startDate
  missedBehavior?: MissedBehavior;
  /** Week-based: fixed assignment per weekday */
  weekSchedule?: WeekDayAssignment[];
  createdAt: string;
  status: "active" | "paused";
};

// ── Habit types ───────────────────────────────────────────────────────────────

export type HabitFrequency = "daily" | "weekly" | "monthly";

export type Habit = {
  id: string;
  objectiveId: string;       // required — habit must belong to an objective
  title: string;
  description?: string;
  frequency: HabitFrequency;
  /** Days of week (0=Sun…6=Sat) — used when frequency is "weekly" with specific days */
  specificDays?: number[];
  startDate: string;         // YYYY-MM-DD
  completedDates: string[];  // YYYY-MM-DD dates on which this habit was completed
  createdAt: string;
};
